fix: updates required for latest hardhat and defender versions
OpenZeppelin/workshops pull request #14
Opened 2021-11-07 03:56 UTC by ivelin

See individual commit comments.

2021-11-12 12:36 UTC, mverzilli requested changes
Thanks for the suggestions @ivelin! I wouldn't merge this telling people to `npm update`, since that really depends on the moment it is run. I prefer to pin the right versions on package.json so `npm install` will do the right thing.

2021-11-12 12:36 UTC, mverzilli commented on 05-upgrades-management/code/README.md
> +`npm update`
This is too disruptive and env dependent. Let's update the package.json instead

2021-11-12 13:38 UTC, ivelin commented
Makes sense. Thank you for reviewing the PR.

On Fri, Nov 12, 2021 at 6:36 AM Martin Verzilli ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for the suggestions @ivelin <https://github.com/ivelin>! I
> wouldn't merge this telling people to npm update, since that really
> depends on the moment it is run. I prefer to pin the right versions on
> package.json so npm install will do the right thing.
> ------------------------------
>
> In 05-upgrades-management/code/README.md
> <https://github.com/OpenZeppelin/workshops/pull/14#discussion_r748250087>:
>
> > @@ -10,14 +10,16 @@ Check out this folder to your local environment, and run:
>
>  `npm install`
>
> +`npm update`
>
> This is too disruptive and env dependent. Let's update the package.json
> instead
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenZeppelin/workshops/pull/14#pullrequestreview-804756637>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARBUFLLONNL7D2GXAY2AGDULUC6RANCNFSM5HQK5TLQ>
> .
>

2021-11-15 12:55 UTC, mverzilli approved these changes
Looks good, thanks!

2021-11-15 12:55 UTC, merged

2021-11-15 15:04 UTC, ivelin commented
Awesome, thanks!

On Mon, Nov 15, 2021 at 6:55 AM Martin Verzilli ***@***.***>
wrote:

> Merged #14 <https://github.com/OpenZeppelin/workshops/pull/14> into
> master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenZeppelin/workshops/pull/14#event-5618058872>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARBUFJP3ZYZ6APK5P3YVO3UMD7NXANCNFSM5HQK5TLQ>
> .
>